# Dockerfile.rails
FROM ruby:3.0.2-buster AS rails-toolbox

ARG USER_ID
ARG GROUP_ID

ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

RUN gem install rails bundler
RUN chown -R user:user $INSTALL_PATH
WORKDIR $INSTALL_PATH

CMD ["/bin/sh"]
